### PR TITLE
First pass at jekyllifaction

### PR DESCRIPTION
**Pull request by ahnlak**
Ok, this is a first pass at moving from a pure static site to something more Jekyll-based - this so that we can easily drop in stuff like the "community tutorials" (https://github.com/32blit/32blit-tutorials-contrib) (for want of a better title) and it all gets formatted right.

It does a *fair* job right now, but I need to go through and fix up some of the formatting in that repo - some of the formatting doesn't quite sit happily with Jekyll's MD parser but this sort of shows the direction I was thinking of.

Any help, or a terrible idea? ;-)

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you! I'm inclined to believe that *any* idea is better than leaving this site, and the tutorials, to stagnate.

I very much need to give myself a crash course in jekyll so I'm not just nodding and smiling though 😆 

One of the issues we discussed when working on the tutorials was how to implement the multi-tabbed code examples- I think you're a DotNet guy so you might remember the C# / VB.Net tabs in Microsoft docs? We were aiming for that... but with no clear idea how to actually pull it off (to be fair, it involved no research and just the assumption it would be possible). I guess this might be an example of funky syntax?

**Comment by ahnlak** [comment]
Ahh, the "different languages in one tabbed panel" type thing? Yeah, I think I know what you mean - I know how I'd do it in Hugo, will have to do some rummaging to see if Jekyll lets me do something similar :-)

Sounds like it's the right direction, so I'll take a pass through the `contrib` stuff later and get it to format more sensibly, then we'll actually have something faintly publishable at least!

**Comment by ahnlak** [comment]
Ok, that worked out (mostly) easier than expected - still need to work through the (awesome) Ninja tutorial to get things formatting nicely, but language tabs seem to mostly work.

(there's still work to do to get the code blocks to scroll instead of wrapping, but... I can't face any more CSS fights today)

I'm aware that it's not easy to see the result so here's a temporary rendering of Ninja Episode 3 -> https://www.ahnlak.com/temp/episode-3.html

(obviously the links and stuff are a bit broken, but the layout should be... showing a direction?)

**Comment by ahnlak** [comment]
Ok, in theory I've updated the community tutorials and re-synced the submodule, so this *should* be a reasonably deployable update.

I'm not sure how (if?) it's possible to test without just putting it live, though :rofl:

**Comment by Gadgetoid** [comment]
> without just putting it live, though

I guess we just put it live! It's not like the site is drowning in traffic or especially useful as it stands!

**Pull request merged**
