### PR TITLE
Add vector svg logo

### PR DESCRIPTION
**Pull request by tansiret**
Hi! I have created a vector version of the logo which I also uploaded to Wikimedia Commons (https://commons.wikimedia.org/wiki/File:32blit_logo.svg) with @ahnlak 's permission. I have replaced logo.png with that as logo.svg and edited base.html accordingly.

### CODE REVIEW

**Comment by Daft-Freak** [comment]
Looks like the original image is still embedded in there.

**Comment by tansiret** [comment]
> Looks like the original image is still embedded in there.

@Daft-Freak how? I added image.svg to base.html

**Comment by tansiret** [comment]
Oh wait sorry, I saw it. I forgot to delete image inside logo lol.

**Comment by Gadgetoid** [comment]
Nice idea, thank you. Should be possible to squash this a little by removing all the inkscape guff. svgo gives me:

32blit-o

Or:

```
<svg xmlns="http://www.w3.org/2000/svg" width="130" height="130"><path d="M0 0h130v130H0Z" style="display:inline;stroke-width:7.83737;stroke-linecap:square;paint-order:stroke fill markers"/><path d="M110 10h10v30h-10ZM10 90h10v30H10Zm70-20h10v10H80Z" style="display:inline;fill:#0f0;stroke-width:1.04421;stroke-linecap:square;paint-order:stroke fill markers"/><path d="M10 50h40v10H10Zm0-20h40v10H10Zm10 80h20v10H20Zm0-30h20v10H20ZM10 10h40v10H10Zm40 0h10v50H50Zm20 40h50v10H70Zm0-20h40v10H70Zm0-20h40v10H70Zm0 30h10v10H70Zm10 50h10v30H80Zm20-20h10v50h-10zm-40 0h10v50H60ZM40 80h10v40H40ZM10 70h10v20H10Zm100 40h10v10h-10zm0-30h10v10h-10z" style="display:inline;fill:#fff;stroke-width:1.20575;stroke-linecap:square;paint-order:stroke fill markers"/></svg>
```

**Review by tansiret — COMMENTED** [review]
@Gadgetoid done!

**Comment by Gadgetoid** [comment]
Welp, let's go full send and see if it updates 😆 

Thank you.

**Comment by tansiret** [comment]
It seems like the files are updated but the main page code isn't. 
image

**Comment by Daft-Freak** [comment]
I think everyone _may_ have been too focused on the image itself and missed: https://github.com/32blit/32blit-website/blob/8f5728dbaeb73896483a4996874fd8663b3937d9/_layouts/base.html#L315
:laughing:

**Comment by Gadgetoid** [comment]
Me, miss something? Naaah. Never happens.

**Comment by tansiret** [comment]
Just [opened PR](https://github.com/32blit/32blit-website/pull/3)

**Pull request merged**
